@startuml
skinparam roundCorner 15
Terraform -> Provider: Send make resource
Provider --> Api: Convert configuration to payload
Api --> Api: Validate if the states are not created
Api --> Provider: Response Validation
Provider --> Terraform: Return information of resources to update
Terraform -> Provider: confirm changes
Provider --> Api: Execute changes
@enduml
